### ISSUE TITLE
HTTP 400 response from PagerDuty

### ISSUE THREAD

**Issue by doreplado** [rundeck-plugins/pagerduty-notification#10]
I'm running into an issue where I'm getting a 400 response from the pagerduty events url. When investigating, it seems like my service_key isn't getting set based on:

> DEBUG: service_key=null

I've tried setting 
> service_key=_mykey_

as well as

> framework.plugin.Notification.PagerDutyNotification.service_key=_mykey_ 

in the framework.properties but I get the null response regardless. 

Any direction or guidance is much appreciated!

**Comment by doreplado** [comment]
To add, I'm using Rundeck 2.7.2-1 and the master version of this repo.

**Comment by doreplado** [comment]
Attached is the exception from the service.log
[rundeck-service.txt](https://github.com/rundeck-plugins/pagerduty-notification/files/1096511/rundeck-service.txt)

**Comment by ahonor** [comment]
@doreplado There's a new fix: https://github.com/rundeck-plugins/pagerduty-notification/pull/11

**Comment by doreplado** [comment]
Thanks Alex!

I've tried pulling in the new version but I still get the same exception. I've got the following in /etc/rundeck/framework.properties and /opt/rundeck-defaults/framework.properties

```framework.plugin.Notification.PagerDutyNotification.service_key=xxxblahblahblahmykeyxxx```

As well as the following in /etc/rundeck/project.properties and /opt/rundeck/defaults/project.properties

```project.plugin.Notification.PagerDutyNotification.service_key=xxxblahblahblahmykeyxxx```

I've also tried just setting it as "service_key=xxx" as well as setting it as a parameter in the jobs themselves. 

They all yield the same result that is the attached exception. Is the DEBUG: service_key=null a red herring or does that mean rundeck / plugin really doesn't see the service key as set?
[pagerduty-plugin-error.txt](https://github.com/rundeck-plugins/pagerduty-notification/files/1097824/pagerduty-plugin-error.txt)

**Comment by doreplado** [comment]
Also if its of any help, I'm running the 2.7.2 version of https://hub.docker.com/r/jordan/rundeck/tags/

**Comment by ltamaster** [comment]
Hi @doreplado 

I got a similar error, and my problem was the server key.
What do you get if you call the endpoint with curl 

 ```
curl -H "Content-type: application/json" -X POST \
    -d '{
     "service_key": "xxxblahblahblahmykeyxxx",
      "event_type": "trigger",
      "description": "FAILURE for production/HTTP on machine srv01.acme.com",
      "details": {
        "ping time": "1500ms",
        "load avg": 0.75
      }
    }' \
    "https://events.pagerduty.com/generic/2010-04-15/create_event.json"

```

Luis

**Comment by doreplado** [comment]
Thanks for the reply Luis :)

I took the key in the framework.proprties and crafted a descriptor json and put it in a file payload.json and then ran it from the rundeck instance in question and it worked fine. The error I get from rundeck is 400 which leads me to believe something is incorrectly formed. 

```a48137a6cb2a:~# curl -vv -H "Content-type: application/json" -X POST -d @payload.json "https://events.pagerduty.com/generic/2010-04-15/create_event.json"
* Hostname was NOT found in DNS cache
*   Trying 54.244.255.45...
* Connected to events.pagerduty.com (54.244.255.45) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS Unknown, Unknown (22):
* SSLv3, TLS handshake, Client hello (1):
* SSLv2, Unknown (22):
* SSLv3, TLS handshake, Server hello (2):
* SSLv2, Unknown (22):
* SSLv3, TLS handshake, CERT (11):
* SSLv2, Unknown (22):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv2, Unknown (22):
* SSLv3, TLS handshake, Server finished (14):
* SSLv2, Unknown (22):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv2, Unknown (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv2, Unknown (22):
* SSLv3, TLS handshake, Finished (20):
* SSLv2, Unknown (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv2, Unknown (22):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
*        subject: OU=GT12858685; OU=See www.rapidssl.com/resources/cps (c)14; OU=Domain Control Validated - RapidSSL(R); CN=*.pagerduty.com
*        start date: 2014-09-16 17:18:11 GMT
*        expire date: 2018-11-17 22:54:29 GMT
*        subjectAltName: events.pagerduty.com matched
*        issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA - G3
*        SSL certificate verify ok.
* SSLv2, Unknown (23):
> POST /generic/2010-04-15/create_event.json HTTP/1.1
> User-Agent: curl/7.38.0
> Host: events.pagerduty.com
> Accept: */*
> Content-type: application/json
> Content-Length: 218
> 
* upload completely sent off: 218 out of 218 bytes
* SSLv2, Unknown (23):
< HTTP/1.1 200 OK
* Server nginx is not blacklisted
< Server: nginx
< Date: Mon, 26 Jun 2017 20:40:29 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 98
< Connection: keep-alive
< 
* Connection #0 to host events.pagerduty.com left intact
{"status":"success","message":"Event processed","incident_key":"4ff2817b914f41c3a3cb94d5089c9ced"}```

**Comment by ltamaster** [comment]
So, the key seems to be ok.

Are you saving the project settings on the database?
You can try:

- removing the settings from framework.properties (you need to restart rundeck)
- on the GUI go to the project configure page and  go to "Edit Project Configuration File"
- Setting the service_key there
<img width="861" alt="screenshot 2017-06-26 17 03 46" src="https://user-images.githubusercontent.com/6034968/27560262-8e9cfdd4-5a91-11e7-8788-930e03d57317.png">

It worked for me with that way.

Luis

**Comment by doreplado** [comment]
Thanks Luis :)

I gave that a shot and also a few variations with no luck. Out of curiosity, what version of rundeck are you running? Maybe I'll just bite the bullet and try upgrading. 

Cheers,
Andrew

**Comment by ltamaster** [comment]
I am using the last rundeck version (launcher with java 8 on linux).

**Comment by ndewing** [comment]
The log was showing `DEBUG: service_key=null` which points to service_key not being picked up or is set incorrectly. You can set the `service_key` at the framework (global) or project level. The entry you enter in your configuration file is specific to if it is a framework or project level configuration (ie: project level configurations go in a the project configuration file).

* Framework properties is in one of these two locations: `/etc/rundeck/framework.properties` or `$RDECK_BASE/etc/framework.properties`
  * Your entry would be: `framework.plugin.Notification.PagerDutyNotification.service_key=xx123049e89dd45f28ce35467a08577yz`
* Project properties is in `$RDECK_BASE/projects/[PROJECT-NAME]/etc/project.properties`.
  * Your entry would be: `project.plugin.Notification.PagerDutyNotification.service_key=xx123049e89dd45f28ce35467a08577yz`

You might want to review: http://rundeck.org/docs/administration/configuration-file-reference.html

**Comment by fdevans** [comment]
Closing this thread due to age.  If there are still issues with the plugin please open a new issue.
